version: '3.7'
services:

  formation-db:
    container_name: formation-db
    image: postgres:14-alpine
    restart: always
    environment:
      - LANG=fr_FR.utf8
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
      - POSTGRES_DB=formation
      - POSTGRES_USER=formation_user
      - POSTGRES_PASSWORD=formation_password
    ports:
      - "45432:5432"
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c session_preload_libraries=auto_explain -c auto_explain.log_min_duration=500 -c max_connections=50 -c stats_temp_directory=/tmp
    volumes:
      - ./docker/data/postgresql/formation:/var/lib/postgresql/data
    networks:
      db:

networks:
  db:
