insert into ref_partenaires(code, libelle)
values ('003', 'ACCORD'),
       ('004', 'COFIDIS'),
       ('005', 'SG PREMIER'),
       ('006', 'PRINTEMPS'),
       ('007', 'PRINTEMPS OLD'),
       ('008', 'CL KIOSQUE'),
       ('009', 'BNP PREMIER'),
       ('010', 'BNP TELESERVICE'),
       ('011', 'CEP SATELLIS'),
       ('012', 'FAE ADL'),
       ('013', 'CL PREMIER'),
       ('014', 'CL LIBRE COURS'),
       ('015', 'CREDIT DU NORD +'),
       ('016', 'CN PREMIER'),
       ('017', 'CMUTUEL'),
       ('018', 'DIVERS MAILING'),
       ('019', 'SCALBERT D.'),
       ('020', 'WANADOO'),
       ('021', 'AIR FRANCE'),
       ('022', 'QUELLE'),
       ('023', '3 SUISSES'),
       ('024', 'CL PRO'),
       ('026', 'SG PRO'),
       ('027', 'MAGAZINES ON LINE'),
       ('028', 'CL AVANTAGES'),
       ('029', 'BONPRIX'),
       ('030', 'LA BQ POSTALE MASTERCARD_VISA'),
       ('031', 'ALAPAGE'),
       ('032', 'CARREFOUR'),
       ('033', 'TF1 TELESHOPPING'),
       ('034', 'BRED'),
       ('035', 'CL CARTE VISA CLEO'),
       ('036', 'HSBC PREMIER'),
       ('037', 'VIRGIN VIP'),
       ('038', 'M6 BOUTIQUE'),
       ('039', 'CIC PARCOURS J'),
       ('040', 'BANQUE POPULAIRE DOMINO'),
       ('041', 'BAGOO'),
       ('042', 'TEOZ'),
       ('043', 'SG FIDELISATION'),
       ('044', 'CAISSE D''EPARGNE PROXIMITE'),
       ('045', 'BANQUE POPULAIRE'),
       ('046', 'E.LECLERC'),
       ('047', 'CREDIT LYONNAIS INFINITE'),
       ('048', 'BARCLAYS'),
       ('049', 'ONEY'),
       ('050', 'INTERNET MARQUE BLANCHE ADL'),
       ('051', 'LA REDOUTE'),
       ('052', 'CREDIT AGRICOLE'),
       ('053', 'FRANCE ABONNEMENTS'),
       ('054', 'PLUSDEMAGS.COM'),
       ('055', 'LA POSTE'),
       ('056', 'PROG DE FID DIVERS'),
       ('057', 'HSBC VISA'),
       ('058', 'SG PROXIMITE'),
       ('059', 'AXA'),
       ('060', 'ATLAS'),
       ('061', 'CEPARGNE'),
       ('062', 'CREDIT AGRICOLE MOZAÏC'),
       ('063', 'GROUPAMA'),
       ('064', 'BOUYGUES TELECOM'),
       ('065', 'SG JAZZ'),
       ('066', 'CORA ADL'),
       ('067', 'LA BQ POSTALE 1er'),
       ('068', 'WONDERBOX'),
       ('069', 'CORA MALIN'),
       ('070', 'CLUB AVANTAGES'),
       ('071', 'BANQUE ACCORD RETAIL'),
       ('072', 'SG PACK JEUNES'),
       ('073', 'BOULANGER'),
       ('074', 'SWISSLIFE'),
       ('075', 'BNP VIF ARGENT'),
       ('076', 'MAXICOURS'),
       ('077', 'LA BANQUE POSTALE'),
       ('078', 'BNP VISA'),
       ('079', 'BANQUE POP LORRAINE CHAMPAGNE'),
       ('080', 'BANQUE POP RIVES DE PARIS'),
       ('081', 'DIGIKIOSQUE'),
       ('082', 'INTERNET MARQUE BLANCHE ADD'),
       ('083', 'BANQUE POPULAIRE MEDITERRANEE'),
       ('084', 'CEP PREMIER'),
       ('085', 'GROUPAMA LOIRE BRETAGNE'),
       ('086', 'CASINO BANQUE'),
       ('087', 'CARREFOUR FID'),
       ('088', 'CEP GESTION PRIVEE'),
       ('089', 'CEP MAXICOURS'),
       ('090', 'SYSTEME U ADL'),
       ('091', 'APRIL'),
       ('092', 'CDISCOUNT'),
       ('093', 'LA BQ POSTALE PATRIMONIAUX'),
       ('094', 'DARTY'),
       ('095', 'BANQUE POPULAIRE NORD'),
       ('096', 'LA BANQUE TARNEAUD PREMIER'),
       ('097', 'LA BANQUE TARNEAUD PLUS'),
       ('098', 'GROUPAMA CENTRE ATLANTIQUE'),
       ('099', 'GROUPAMA GRAND EST'),
       ('100', 'BANQUE PRIVEE LCL'),
       ('101', 'LA BQ POSTALE PLATINUM'),
       ('102', 'GENERALI'),
       ('103', 'LE CLUB ACCORHOTELS'),
       ('104', 'BANQUE POPULAIRE ATLANTIQUE'),
       ('105', 'GROUPAMA MEDITERRANEE'),
       ('106', 'CREDIT SOCIAL DES FONCTIONNAIRES'),
       ('107', 'FNAC'),
       ('108', 'GROUPAMA PARIS VAL DE LOIRE'),
       ('109', 'GROUPAMA NORD EST'),
       ('110', 'BNP PRIORITY'),
       ('111', 'LCL CARTE INVENTIVE'),
       ('112', 'CARREFOUR BANQUE'),
       ('113', 'CAMAIEU'),
       ('114', 'WONDERBOX'),
       ('115', 'CONFORAMA'),
       ('116', 'DAMART MAGAZINES'),
       ('117', 'GROUPAMA RHONE ALPES'),
       ('118', 'MALAKOFF MEDERIC'),
       ('119', 'MEDICIS'),
       ('120', 'MONOPRIX'),
       ('121', 'ATLAS FOR MEN'),
       ('122', 'ENI'),
       ('123', 'CULTURA'),
       ('124', 'SG VISA'),
       ('125', 'IRCEM'),
       ('126', 'PLANET.FR'),
       ('127', 'KING JOUETS'),
       ('128', 'H&M'),
       ('129', 'PAY BY PHONE'),
       ('150', 'BOURSIER'),
       ('151', 'LA REDOUTE.FR'),
       ('152', 'ALICE'),
       ('153', 'PLURIELLES'),
       ('154', 'PLANET VERTBAUDET'),
       ('155', 'PLUSDEPROMO'),
       ('156', 'TICKETNET.FR'),
       ('157', 'RUE DU COMMERCE'),
       ('158', 'CHAMPION'),
       ('159', 'M6 BOUTIQUE ON LINE'),
       ('160', 'ADESIO.FR'),
       ('161', 'CONSOGLOBE'),
       ('162', 'PIXMANIA'),
       ('163', 'CASINO BANQUE WEB'),
       ('164', 'TOP ACHAT ADL'),
       ('165', 'LASTMINUTE.COM'),
       ('166', 'AUCHAN'),
       ('167', 'FP PLUS UTILISE'),
       ('168', 'CARREFOUR ON LINE'),
       ('169', 'CORA WEB'),
       ('170', 'CANAL PLUS'),
       ('171', 'RELAY'),
       ('172', '2xmoinscher'),
       ('173', 'Mouvango'),
       ('174', 'FP PLUS UTILISE'),
       ('175', 'UGC'),
       ('176', 'VIKING DIRECT'),
       ('177', 'ZINEWAY.FR'),
       ('178', 'KIOSQUE HYBRIDE PLUSDEMAGS'),
       ('179', 'SFR'),
       ('180', 'DECITRE.FR'),
       ('181', 'BLANCHE PORTE'),
       ('182', 'KIABI'),
       ('183', 'RTL'),
       ('184', 'RTL2'),
       ('185', 'FUN RADIO'),
       ('195', 'CODES FOR GIFT'),
       ('196', 'LA PLACE DIGITALE'),
       ('197', 'COFFRET CADEAU FNAC'),
       ('198', 'KIOSQUE CADEAU'),
       ('300', 'CE OFFREURS'),
       ('301', 'CE DIFFUSEURS'),
       ('302', 'PARTENAIRES CE'),
       ('303', 'PETITS CLUBS ET COOPS'),
       ('304', 'KALIDEA'),
       ('305', 'MEYCLUB'),
       ('306', 'RESEAU CEZAM'),
       ('307', 'FIDELISATION EASIALY'),
       ('310', 'ADMINISTRATIONS ET ENTREPRISES'),
       ('311', 'ATAC'),
       ('312', 'CORA'),
       ('313', 'DIVERS'),
       ('314', 'INTER CE'),
       ('315', 'INTERMARCHE'),
       ('316', 'IRIS'),
       ('317', 'MG'),
       ('318', 'PRIVIS FAE'),
       ('319', 'SA'),
       ('320', 'SNCF'),
       ('321', 'SU'),
       ('322', 'TPS'),
       ('323', 'CLUB INTERNET'),
       ('324', 'CHAPITRE.COM'),
       ('325', 'CORA MALIN'),
       ('326', 'SU SWEEP'),
       ('327', 'ALAPAGE.COM'),
       ('328', 'Go Sport'),
       ('329', 'LECLERC'),
       ('330', 'MATCH'),
       ('331', 'MYPIX'),
       ('332', 'PIXMANIA'),
       ('333', 'VENTES PRIVEES INTERNET ADD'),
       ('334', 'Rue du Commerce'),
       ('335', 'CREODIS'),
       ('336', 'CARREFOUR FIDELITE'),
       ('350', 'OFUP'),
       ('400', 'AL CAMPO'),
       ('401', 'CARREFOUR'),
       ('501', 'GREEN'),
       ('502', 'GOLD'),
       ('503', 'PLATINIUM'),
       ('504', 'CENTURION'),
       ('505', 'Capital One'),
       ('506', 'Amex Blue'),
       ('507', 'American Express'),
       ('510', 'FIRST DIRECT'),
       ('515', 'GOLDSHORE'),
       ('520', 'HALIFAX'),
       ('530', 'MARBLES'),
       ('531', 'GM CARD'),
       ('532', 'BENIFICIAL'),
       ('540', 'HSBC'),
       ('545', 'Lloyds TSB'),
       ('550', 'MKM'),
       ('560', 'MS Blue'),
       ('561', 'MS Black'),
       ('562', 'MS Gold'),
       ('563', 'MS Platinium'),
       ('564', 'Morgan Stanley'),
       ('570', 'Direct Line'),
       ('571', 'RBS Advanta'),
       ('572', 'RBS'),
       ('573', 'Nat West'),
       ('574', 'Nat West Commercial'),
       ('575', 'STYLE'),
       ('576', 'Ulster Bank'),
       ('577', 'Air Miles'),
       ('580', 'Something4'),
       ('585', 'Unknown'),
       ('590', 'House'),
       ('600', 'SAGA'),
       ('610', 'CSMA'),
       ('620', 'Caravan Club'),
       ('630', 'EGG'),
       ('640', 'CAHOOT'),
       ('650', 'MARKS & SPENCER'),
       ('660', 'FIRST DIRECT STAFF'),
       ('670', 'Paragon Laundry'),
       ('671', 'L Oreal'),
       ('672', 'The MDU'),
       ('678', 'MBNA'),
       ('713', 'ADLP Assurances'),
       ('715', 'LEOO'),
       ('718', 'ADLP Telesurveillance'),
       ('900', 'PCH');
